### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by mbrookes** [vazco/meteor-universe-accounts-ui#3]
I understand this is intended to be supported by universe:modules, which universe:accounts-ui depends on? I also tried manually adding universe:modules to packages, but no change.

Any advice appreciated.

**Comment by MacRusher** [comment]
Could you show your code somehow?
But I guest that you're trying to use `import` statement in plain `.js` or `.jsx` file. Instead you must suffix your file with `.import.js` or `.import.jsx` for `universe:modules` to kick in.

If you still want to import a module in plain js(x) file you can use dynamic imports like `System.import('/absolute/path/to/module').then(module => console.log('My module:', module))`

In case of `universe:accounts-ui` you can try something like

```
System.import('{universe:accounts-ui}').then(({ComboBox}) => React.render(<ComboBox />, domElement))
```

I hope you get the point :) But I encourage to use modules and `.import.jsx` files, just remember to import it from plain js file to start the app.

**Comment by mbrookes** [comment]
Thanks, yes, that was the problem.

**Comment by cristo-rabani** [comment]
Also you can try import with package universe:ecmascript
