### ISSUE TITLE
Incompatible with latest Babel-Compiler

### ISSUE THREAD

**Issue by batjko** [vazco/meteor-universe-accounts-ui#4]
Hi there,

Just tried to add it to my project and encountered this error:

> Conflict: Constraint babel-compiler@5.8.24_1 is not satisfied by babel-compiler
> 6.5.2.

![image](https://cloud.githubusercontent.com/assets/7287076/14248602/5d3ea0c4-fa6d-11e5-8101-c170f57a24cf.png)

What's the best thing to do here?

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
