### ISSUE TITLE
Constraint universe:modules@0.6.1 is not satisfied by universe:modules 0.1.0

### ISSUE THREAD

**Issue by stolinski** [vazco/meteor-universe-accounts-ui#5]
Just tried to add package and am getting

```
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint universe:modules@0.6.1 is not satisfied by
universe:modules 0.1.0.
Constraints on package "universe:modules":
* universe:modules@0.6.1 <- universe:accounts-ui 0.1.4
```

On Meteor 1.3.2.2

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
