### ISSUE TITLE
Error messages i18N

### ISSUE THREAD

**Issue by alexismoreau** [vazco/meteor-universe-accounts-ui#9]
Hello,

First of all, I wanted to thank you for your work on this package.

I succeeded to translate almost every string of your package but the error messages are still in english.
As you can see here : 
https://github.com/vazco/meteor-universe-accounts-ui/blob/bfafef62e3003a73465fbcc931f463bf23ea20cc/components/ErrorMessages.jsx#L13

Maybe you can get inspired by this package : 
https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/443e852cb0471fa83c090119e64d10b9a5eb9355/login_buttons_dropdown.js#L511

Please let me know you thoughts about this.

**Comment by kestarumper** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
